name: Deploy TriFetch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          clean: true
          
  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Authenticate Docker to Google Cloud
        run: gcloud auth configure-docker gcr.io
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/trifetch-backend:${{ github.sha }},gcr.io/${{ secrets.GCP_PROJECT_ID }}/trifetch-backend:latest
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy trifetch-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/trifetch-backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "NODE_ENV=production,PORT=8080,GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }},GCP_PROCESSED_BUCKET_NAME=${{ secrets.GCP_PROCESSED_BUCKET_NAME }}" 